### ISSUE TITLE
[Bug] App-oulet doesn't show available apps

### ISSUE THREAD

**Issue by haggen88** [app-outlet/app-outlet#101] opened 2020-07-26 06:05 UTC
**Describe the bug**
Opening the application in AppImage does not load any category or applications. It only shows error messages.

**To Reproduce**
1. open App.Outlet-1.3.2.AppImage

**Expected behavior**
Load the categories and show the available applications.

**Screenshots**
![app oulet](https://user-images.githubusercontent.com/68134588/88471997-fd899280-cedc-11ea-842f-95aee45ce219.png)
![app oulet2](https://user-images.githubusercontent.com/68134588/88472188-3aa25480-cede-11ea-86a2-768773bcb41f.png)

**Desktop (please complete the following information):**
Linux Mint 20.04
Cinnamon 4.6.6
Flatpak 1.8.1 / Flathub repo
Kernel 5.4.0-42-generic
Firefox 78.0.2
No internet connection problems [with firewall disabled]

**Additional context**
I downloaded the app [like Appimage and .deb] from [here](https://github.com/app-outlet/app-outlet/releases/tag/v1.3.4). The release appears as _1.3.4 and the application is named as 1.3.2_. Both present the same problem. I downloaded the Appimage version 1.3.1 [like Appimage and .deb] and it also has problems.

Both Flathub and AppImageHub at the time of the bug appear online.

In my system I manage the Appimage app with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) but when testing the .deb versions I rule out that this was the problem.

Recently I have not made any major changes to the system .. just change language settings. Region and Time format [Es] are with another language of the interface language [En].  I revert the language configuration changes and the error still persists. I tested it in versions 1.3.4 and 1.3.1 like Appimage [with and without AppimageLauncher] and .deb.

A week ago it worked fine ... [maybe it could be the API].

---
Best regards!
[btw a very useful app, please consider a flatpak version]

**Comment by sciroccogti82** [comment] 2020-07-26 10:11
Same problem here on manjaro

**Comment by MessiasLima** [comment] 2020-07-27 10:43
I verified the problems you presented.

**About the name of the files on the release:**
Thank you for aware us about it. It was just a naming problem. It was already renamed.

**About the application not working**
It is because we use Heroku free tier. We don't have earnings enough to have a dedicated infrastructure.
So, depending on usage, our server may enter on Sleep mode at the end of the month. It will work normally on next month.
This is duplicate of #70 

Thank you for your support.

**Closed by MessiasLima** 2020-07-27 10:43 UTC
