### ISSUE TITLE
Website Appears Down

### ISSUE THREAD

**Issue by digitaleagle** [app-outlet/app-outlet#73] opened 2019-10-26 18:04 UTC
When clicking on the Debian Package Download link, it takes me to this page: https://appoutlet.herokuapp.com/download/deb

The page just has this on it:

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
> heroku logs --tail

**Comment by MessiasLima** [comment] 2019-10-28 09:43
duplicate of #70

**Closed by MessiasLima** 2019-10-28 09:43 UTC
Labels: duplicate
